name: conduit_api_testing.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

env:
  ENV_TYPE: 'staging'

jobs:
  run-api-tests:
    name: Run API tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # Automates dependency caching for npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run API tests
        run: npx playwright test

      - name: Upload Allure Results as Artifact
        if: always() && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: allure_results
          path: allure_results
  generate-and-publish-report:
      name: Generate and Publish Allure report
      if: always() && !cancelled() && github.ref == 'refs/heads/main'
      needs: run-api-tests
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Setup JAVA
          uses: actions/setup-java@v3
          with:
            distribution: 'microsoft'
            java-version: '17'

        - name: Download Allure CLI
          run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz && sudo tar -zxvf allure-2.34.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.34.1/bin/allure /usr/bin/allure

        - name: Download all workflow run artifacts
          uses: actions/download-artifact@v4

        - name: Generate Allure report
          run: allure generate -c allure_results -o _site

        - name: Store generated report
          uses: actions/upload-artifact@v4
          with:
            name: _site
            path: _site
            retention-days: 1

        - name: Download all workflow run artifacts
          uses: actions/download-artifact@v4

        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v3

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
        - name: Show Report Link
          run: echo "https://boda4ek888.github.io/qa_pw_coffee_cart_github_actions/"
